FROM node:22-bookworm-slim

# 필수 패키지 설치 및 업데이트
RUN apt-get update && apt-get install -y \
    python3 \
    g++ \
    make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/TediCross/

COPY tmp/ .

RUN npm install --omit=dev

VOLUME /opt/TediCross/data/

ENTRYPOINT ["/usr/local/bin/npm"]
CMD ["start", "--", "-c", "data/settings.yaml"]
