name: summerwind-actions-runner

on:
  push:
    paths:
      - ".github/workflows/summerwind-actions-runner.yaml"
      - "summerwind-actions-runner/**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 00:00 on Sunday.
    # https://crontab.guru/#0_0_*_*_7
    - cron: "30 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        summerwind-actions-runner-version:
          - "latest"
    steps:
      - name: Env
        run: |
          env | sort
      - uses: actions/checkout@v5
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Handle keyserver connections
        run: |
          wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
      - name: Generate Dockerfile
        run: |
          cat ${PROJECT}/Dockerfile.template | docker run -i --rm subfuzion/envtpl > ${PROJECT}/Dockerfile ;
        env:
          PROJECT: ${{ github.workflow }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.workflow }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest
          provenance: false
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
